import Hero from '../Molecules/Hero';
import ContentSwap from '../Molecules/ContentSwap';
import Caption from '../Atoms/Caption';

import { IAppSection } from '../../interfaces';

const AboutSection = ({ id }: IAppSection) => (
  <section id={id} className="w-full">
    <Hero
      dividerClassRef={'bg-divider-about top-0'}
      className={'bg-brand-medium-blue'}
    >
      <div className={'pt-20 xl:pt-[100px]'} />
      <ContentSwap
        aSideContent={
          <img
            src="/about-hydra.png"
            className="mx-auto mr-auto w-full max-w-sm md:max-w-md lg:max-w-lg xl:max-w-xl"
            alt={'about hydranet'}
          />
        }
        bSideContent={
          <>
            <Caption hashLabel={'About Us'} title={'What is Hydranet?'} />
            <div className={'font-light text-brand-greyed'}>
              <p className={'font-light text-current'}>
                Hydranet DAO is an organization focused on developing
                “abstractive interoperability”. Our key focus is on solutions
                that allow fundamentally-incompatible blockchains like Bitcoin
                and Ethereum to interoperate with each other using Layer 3
                abstractions. Layer 3, to Hydranet, is the bridge where
                differing and otherwise-isolated Layer 2 protocols like
                Bitcoin’s Lightning Network and Ethereum’s Connext state channel
                network communicate and exchange information.
              </p>
              <p className={'mt-3 font-light text-current'}>
                HDX is an Arbitrum token based on the (3,3) Protocol-owned
                Liquidity model pioneered by OlympusDAO. HDX rewards are
                generated by bonding funds to the protocol to provide it with
                further liquidity. HDX will additionally serve as the meta-token
                of our Layer 3 DEX, receiving all fees collected from the
                Hydranet ecosystem and future DeFi services.
              </p>
            </div>
          </>
        }
      />
    </Hero>
  </section>
);

export default AboutSection;
