import type { NextPage } from 'next';
import Head from 'next/head';

import Layout from '../src/components/Templates/Layout';
import HomeHero from '../src/components/Molecules/HomeHero';
import Hero from '../src/components/Molecules/Hero';
import ContentSwap from '../src/components/Molecules/ContentSwap';
import Caption from '../src/components/Atoms/Caption';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <HomeHero />
        <Hero
          dividerClassRef={'bg-divider-top-right top-0'}
          className={'bg-brand-darker-blue'}
        >
          <ContentSwap
            aSideContent={
              <img
                src="/placeholder-1.png"
                className="mx-auto w-full max-w-sm md:max-w-md"
              />
            }
            bSideContent={
              <>
                <Caption
                  hashLabel={'explain like im five'}
                  title={'About Hydranet'}
                />
                <p className={'mt-3 font-light text-brand-greyed'}>
                  Hydranet DAO is a platform focused on Abstractive
                  Interoperability – making fundamentally-incompatible
                  decentralized crypto networks like Bitcoin and Ethereum talk
                  fluently by way of Layer 3 abstraction with EVM-centric smart
                  contracts and state channels, and Bitcoin/UTXO-based off-chain
                  protocols like the Lightning Network.
                </p>
                <p>
                  HDX is an Arbitrum token based on the (3,3) Protocol-owned
                  Liquidity model pioneered by OlympusDAO.
                </p>
                <p>
                  HDX rewards are generated by bonding funds to the protocol to
                  provide it further liquidity and by staking to help secure the
                  network. HDX will additionally serve as the meta-token of our
                  Layer 3 DEX, being the end recipient of swaps from trading
                  fees and DeFi services.
                </p>
              </>
            }
          />
        </Hero>
      </Layout>
    </>
  );
};

export default Home;
