import type { NextPage } from 'next';
import Head from 'next/head';

import Layout from '../src/components/Templates/Layout';
import HomeHero from '../src/components/Molecules/HomeHero';
import Hero from '../src/components/Molecules/Hero';
import ContentSwap from '../src/components/Molecules/ContentSwap';
import Caption from '../src/components/Atoms/Caption';
import Facts from '../src/components/Molecules/Facts';
import Timeline from '../src/components/Molecules/Timeline';
import Button from '../src/components/Atoms/Button';
import Articles from '../src/components/Molecules/Articles';
import { IArticle } from '../src/interfaces';
import { HYDRANET_MEDIUM_FETCH_URL } from '../src/constants';

export async function getStaticProps(context) {
  let hasErrorFetchingArticles = false;
  let articles: Array<IArticle> = [];

  try {
    const response = await fetch(HYDRANET_MEDIUM_FETCH_URL);
    const { items } = await response.json();
    articles = items;
  } catch (err) {
    hasErrorFetchingArticles = true;
  }

  return {
    props: {
      articles,
      hasErrorFetchingArticles,
    },
  };
}

type HomeProps = {
  articles: Array<IArticle>;
  hasErrorFetchingArticles: boolean;
};

const Home: NextPage<HomeProps> = ({
  articles,
  hasErrorFetchingArticles,
}: HomeProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <HomeHero />

        {/* ABOUT */}
        <Hero
          dividerClassRef={'bg-divider-top-right top-0'}
          className={'bg-brand-medium-blue'}
        >
          <div className={'pt-20 xl:pt-[100px]'} />
          <ContentSwap
            aSideContent={
              <img
                src="/placeholder-1.png"
                className="lg:mxl mx-auto mr-auto w-full max-w-sm md:max-w-md lg:max-w-lg xl:max-w-xl"
              />
            }
            bSideContent={
              <>
                <Caption
                  hashLabel={'explain like im five'}
                  title={'About Hydranet'}
                />
                <div className={'font-light text-brand-greyed'}>
                  <p className={'font-light text-current'}>
                    Hydranet DAO is a platform focused on Abstractive
                    Interoperability – making fundamentally-incompatible
                    decentralized crypto networks like Bitcoin and Ethereum talk
                    fluently by way of Layer 3 abstraction with EVM-centric
                    smart contracts and state channels, and Bitcoin/UTXO-based
                    off-chain protocols like the Lightning Network.
                  </p>
                  <p className={'mt-3 font-light text-current'}>
                    HDX is an Arbitrum token based on the (3,3) Protocol-owned
                    Liquidity model pioneered by OlympusDAO.
                  </p>
                  <p className={'mt-3 font-light text-current'}>
                    HDX rewards are generated by bonding funds to the protocol
                    to provide it further liquidity and by staking to help
                    secure the network. HDX will additionally serve as the
                    meta-token of our Layer 3 DEX, being the end recipient of
                    swaps from trading fees and DeFi services.
                  </p>
                </div>
              </>
            }
          />
        </Hero>

        {/* DEX PRODUCT */}
        <Hero
          dividerClassRef={'bg-divider-top-left top-0 transform rotate-y-180'}
          className={'bg-brand-darkest-blue'}
        >
          <div className={'pt-20 xl:pt-[100px]'} />
          <ContentSwap
            side={'right'}
            aSideContent={
              <img
                src="/dex.png"
                className="lg:mxl mx-auto mr-auto w-full max-w-sm md:max-w-md lg:max-w-lg xl:max-w-3xl"
              />
            }
            bSideContent={
              <>
                <Caption hashLabel={'product'} title={'HydraDex'} />
                <div className={'font-light text-brand-greyed'}>
                  <p className={'font-light text-current'}>
                    Layer 1: On-chain intranet work transactions. Traditional,
                    limited to one coin.
                  </p>
                  <p className={'mt-3 font-light text-current'}>
                    Layer 2: Off-chain intranet work transactions. Nearly
                    instant, limited to one coin.
                  </p>
                  <p className={'mt-3 font-light text-current'}>
                    Layer 3: Cross-chain internet work transactions. Nearly
                    instant, compatible with multiple coins on multiple
                    networks.
                  </p>
                  <div className="mt-8 text-center uppercase ">
                    <pre>Lazarus build</pre>
                  </div>
                  <div className="mx-auto mt-3 grid w-48 grid-cols-1 gap-8 sm:w-auto sm:grid-cols-3 md:grid-cols-3">
                    <Button>
                      <span className="flex items-center justify-center space-x-3">
                        <img src={'./windows.svg'} className={'w-6'} />
                        <p>Windows</p>
                      </span>
                    </Button>
                    <Button>
                      <span className="mx-auto flex items-center justify-center space-x-3">
                        <img src={'./linux.svg'} className={'w-6'} />
                        <p>Linux</p>
                      </span>
                    </Button>
                    <Button>
                      <span className="flex items-center justify-center space-x-3">
                        <img src={'./apple.svg'} className={'w-6'} />
                        <p>MacOs</p>
                      </span>
                    </Button>
                  </div>
                </div>
              </>
            }
          />
          {/*<div className="mx-auto mt-10 max-w-lg lg:mt-20 lg:max-w-full xl:mt-24">*/}
          {/*  <Facts />*/}
          {/*</div>*/}
        </Hero>

        {/* ROADMAP */}
        <Hero
          dividerClassRef={
            'bg-divider-top-right-2 top-0 transform rotate-y-180'
          }
          className={'bg-brand-darker-blue'}
        >
          <div className={'pt-20 xl:pt-[100px]'} />
          <Caption hashLabel={'roadmap'} title={'Timeline'} />
          <Timeline />
        </Hero>

        {/* ARTICLES */}
        <Hero
          dividerClassRef={
            'bg-divider-top-right-2 top-0 transform rotate-y-180'
          }
          className={'bg-brand-medium-blue'}
        >
          <div className={'pt-20 xl:pt-[100px]'} />
          <Caption hashLabel={'news'} title={'Latest articles'} />
          <Articles
            articles={articles}
            hasErrorFetchingArticles={hasErrorFetchingArticles}
          />
        </Hero>
      </Layout>
    </>
  );
};

export default Home;
